FROM node:9.11.1

RUN mkdir -p /app
WORKDIR /app

RUN npm install react-scripts@2.1.3 -g && \
  npm cache clean --force

ENV PATH /app/node_modules/.bin:$PATH

ENTRYPOINT ["/usr/local/bin/npm", "run"]

CMD ["start-dev"]