version: "3"

services:
  db:
    env_file: .env
    image: postgres
    container_name: psql
    ports:
      - "${POSTGRES_PORT}:5432"

  back:
    build: ./backend
    depends_on:
      - db
    volumes:
      - ./backend:/app
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    command: lein ring server-headless ${BACKEND_PORT}
